### ISSUE TITLE
text size

### ISSUE THREAD

**Issue by zamalex** [Dimezis/BottomNavigationBar#9]
Is there any way to control the tab text size ? i have a tab called favorites and it shows fav-

**Comment by Dimezis** [comment]
Unfortunately no. PRs appreciated

**Comment by Dimezis** [comment]
_Deleted my previous answer_.

You can override `bottom_bar_title_inactive_font_size` dimension, but it's already just 12sp, so I guess you have to reconsider the amount of your items

**Comment by zamalex** [comment]
thanks for your respond

Sent from Outlook<http://aka.ms/weboutlook>
________________________________
